"use client";
import { useState } from "react";
import { courseCategories, getSubcategories, getSpecializations, levels, timeSlots, ageGroups, gradeGroups } from "@/lib/categories";
import type { Course } from "@/lib/data";
export function CourseClassification({ course }: { course?: Course | null }) {
  const [category,setCategory] = useState(course?.category || courseCategories[0].name);
  const [subcategory,setSubcategory] = useState(course?.subcategory || "");
  const [specialization,setSpecialization] = useState(course?.specialization || "");
  const specialties = getSpecializations(category,subcategory);
  return <><label>Үндсэн ангилал<select name="category" value={category} onChange={e => { setCategory(e.target.value);setSubcategory("");setSpecialization(""); }}>{courseCategories.map(c => <option key={c.name}>{c.name}</option>)}</select></label><div className="form-row"><label>Дэд төрөл<select name="subcategory" value={subcategory} onChange={e => { setSubcategory(e.target.value);setSpecialization(""); }} required><option value="">Дэд төрөл сонгох</option>{getSubcategories(category).map(s => <option key={s.name}>{s.name}</option>)}</select></label>{specialties.length > 0 && <label>Чиглэл / зорилго<select name="specialization" value={specialization} onChange={e => setSpecialization(e.target.value)}><option value="">Ерөнхий</option>{specialties.map(s => <option key={s}>{s}</option>)}</select></label>}</div><div className="form-row"><label>Түвшин<select name="level" defaultValue={course?.level || ""}><option value="">Бүх түвшинд</option>{levels.map(l => <option key={l}>{l}</option>)}</select></label><label>Сургалтын хэлбэр<select name="format" defaultValue={course?.format}>{["Танхим","Онлайн","Хосолсон"].map(f => <option key={f}>{f}</option>)}</select></label></div><fieldset className="choice-fieldset"><legend>Хичээллэх цаг</legend>{timeSlots.map(t => <label key={t}><input type="checkbox" name="time_slots" value={t} defaultChecked={course?.time_slots?.includes(t)}/>{t}</label>)}</fieldset>{category === "Хүүхдийн хөгжил" && <fieldset className="choice-fieldset" key={`${category}-ages`}><legend>Насны бүлэг</legend>{ageGroups.filter(a => a !== "18+").map(a => <label key={a}><input type="checkbox" name="age_groups" value={a} defaultChecked={course?.age_groups?.includes(a)}/>{a} нас</label>)}</fieldset>}{category === "ЕБС & Шалгалтын бэлтгэл" && <fieldset className="choice-fieldset" key={`${category}-grades`}><legend>Анги</legend>{gradeGroups.map(g => <label key={g}><input type="checkbox" name="grade_groups" value={g} defaultChecked={course?.grade_groups?.includes(g)}/>{g}-р анги</label>)}</fieldset>}</>;
}
